# Generated by Django 6.0 on 2026-02-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_agentinvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="id_document",
            field=models.ImageField(blank=True, null=True, upload_to="id_documents/"),
        ),
        migrations.AddField(
            model_name="agent",
            name="id_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="agent",
            name="project_type",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
